/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: ImageWithAlt;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ImageWithAlt)
>;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type RecommendedProduct = {
  _id: string;
  _type: "recommendedProduct";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  brand?: string;
  image?: ImageWithAlt;
  description?: string;
  link?: string;
  order?: number;
};

export type RecommendationsPage = {
  _id: string;
  _type: "recommendationsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  intro?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  body?: BlockContent;
  seo?: Seo;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type DoctorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "doctor";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: DoctorReference;
  coverImage?: ImageWithAlt;
  excerpt?: string;
  body?: BlockContent;
  publishedAt?: string;
  seo?: Seo;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
  group?: "general" | "kids" | "adults";
  order?: number;
};

export type TreatmentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "treatment";
};

export type GalleryItem = {
  _id: string;
  _type: "galleryItem";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  kind?: "clinic" | "beforeAfter";
  image?: ImageWithAlt;
  beforeImage?: ImageWithAlt;
  afterImage?: ImageWithAlt;
  treatment?: TreatmentReference;
  caption?: string;
  consent?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  patientName?: string;
  quote?: string;
  treatment?: TreatmentReference;
  rating?: 5 | 4 | 3 | 2 | 1;
  source?: "google" | "direct";
  consent?: boolean;
};

export type Doctor = {
  _id: string;
  _type: "doctor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  qualifications?: string;
  specialisation?: string;
  registrationNumber?: string;
  photo?: ImageWithAlt;
  bio?: BlockContent;
  order?: number;
};

export type Treatment = {
  _id: string;
  _type: "treatment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  audience?: "kids" | "adults" | "both";
  category?:
    | "preventive"
    | "restorative"
    | "endodontics"
    | "orthodontics"
    | "cosmetic"
    | "prosthetics"
    | "gum-care"
    | "surgery";
  summary?: string;
  image?: ImageWithAlt;
  body?: BlockContent;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _type: "qa";
    _key: string;
  }>;
  related?: Array<
    {
      _key: string;
    } & TreatmentReference
  >;
  order?: number;
  seo?: Seo;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroHeadline?: string;
  heroSubheadline?: string;
  heroImage?: ImageWithAlt;
  trustStats?: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }>;
  featuredTreatments?: Array<
    {
      _key: string;
    } & TreatmentReference
  >;
  featuredDoctors?: Array<
    {
      _key: string;
    } & DoctorReference
  >;
  featuredTestimonials?: Array<
    {
      _key: string;
    } & TestimonialReference
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  tagline?: string;
  logo?: ImageWithAlt;
  phone?: string;
  whatsapp?: string;
  email?: string;
  addressLine1?: string;
  city?: string;
  region?: string;
  postalCode?: string;
  geo?: Geopoint;
  mapsUrl?: string;
  hours?: Array<{
    day?:
      | "Monday"
      | "Tuesday"
      | "Wednesday"
      | "Thursday"
      | "Friday"
      | "Saturday"
      | "Sunday";
    closed?: boolean;
    opens?: string;
    closes?: string;
    _type: "dayHours";
    _key: string;
  }>;
  socialLinks?: Array<{
    platform?: "Instagram" | "Facebook" | "YouTube" | "X" | "LinkedIn";
    url?: string;
    _type: "socialLink";
    _key: string;
  }>;
  googleReviewUrl?: string;
  defaultSeo?: Seo;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type AllSanitySchemaTypes =
  | Seo
  | BlockContent
  | SanityImageAssetReference
  | ImageWithAlt
  | RecommendedProduct
  | RecommendationsPage
  | Page
  | Slug
  | DoctorReference
  | Post
  | Faq
  | TreatmentReference
  | GalleryItem
  | Testimonial
  | Doctor
  | Treatment
  | TestimonialReference
  | HomePage
  | SiteSettings
  | Geopoint
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{  name, tagline, phone, whatsapp, email,  "logo": logo{    alt,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  },  addressLine1, city, region, postalCode, mapsUrl, googleReviewUrl,  hours, socialLinks}
export type SiteSettingsQueryResult = {
  name: string | null;
  tagline: string | null;
  phone: string | null;
  whatsapp: string | null;
  email: string | null;
  logo: {
    alt: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
  addressLine1: string | null;
  city: string | null;
  region: string | null;
  postalCode: string | null;
  mapsUrl: string | null;
  googleReviewUrl: string | null;
  hours: Array<{
    day?:
      | "Friday"
      | "Monday"
      | "Saturday"
      | "Sunday"
      | "Thursday"
      | "Tuesday"
      | "Wednesday";
    closed?: boolean;
    opens?: string;
    closes?: string;
    _type: "dayHours";
    _key: string;
  }> | null;
  socialLinks: Array<{
    platform?: "Facebook" | "Instagram" | "LinkedIn" | "X" | "YouTube";
    url?: string;
    _type: "socialLink";
    _key: string;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{  heroHeadline, heroSubheadline, heroImage, trustStats,  featuredTreatments[]->{  _id, title, "slug": slug.current, audience, category, summary, image},  featuredDoctors[]->{ _id, name, "slug": slug.current, qualifications, specialisation, photo },  featuredTestimonials[]->{ _id, patientName, quote, rating, source }}
export type HomePageQueryResult = {
  heroHeadline: string | null;
  heroSubheadline: string | null;
  heroImage: ImageWithAlt | null;
  trustStats: Array<{
    value?: string;
    label?: string;
    _type: "stat";
    _key: string;
  }> | null;
  featuredTreatments: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    audience: "adults" | "both" | "kids" | null;
    category:
      | "cosmetic"
      | "endodontics"
      | "gum-care"
      | "orthodontics"
      | "preventive"
      | "prosthetics"
      | "restorative"
      | "surgery"
      | null;
    summary: string | null;
    image: ImageWithAlt | null;
  }> | null;
  featuredDoctors: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    qualifications: string | null;
    specialisation: string | null;
    photo: ImageWithAlt | null;
  }> | null;
  featuredTestimonials: Array<{
    _id: string;
    patientName: string | null;
    quote: string | null;
    rating: 1 | 2 | 3 | 4 | 5 | null;
    source: "direct" | "google" | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: treatmentsQuery
// Query: *[_type == "treatment" && defined(slug.current)]  | order(order asc, title asc) {  _id, title, "slug": slug.current, audience, category, summary, image}
export type TreatmentsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  audience: "adults" | "both" | "kids" | null;
  category:
    | "cosmetic"
    | "endodontics"
    | "gum-care"
    | "orthodontics"
    | "preventive"
    | "prosthetics"
    | "restorative"
    | "surgery"
    | null;
  summary: string | null;
  image: ImageWithAlt | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: treatmentBySlugQuery
// Query: *[_type == "treatment" && slug.current == $slug][0]{  _id, title, "slug": slug.current, audience, category, summary, image, body, faqs, seo,  related[]->{  _id, title, "slug": slug.current, audience, category, summary, image}}
export type TreatmentBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  audience: "adults" | "both" | "kids" | null;
  category:
    | "cosmetic"
    | "endodontics"
    | "gum-care"
    | "orthodontics"
    | "preventive"
    | "prosthetics"
    | "restorative"
    | "surgery"
    | null;
  summary: string | null;
  image: ImageWithAlt | null;
  body: BlockContent | null;
  faqs: Array<{
    question?: string;
    answer?: string;
    _type: "qa";
    _key: string;
  }> | null;
  seo: Seo | null;
  related: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    audience: "adults" | "both" | "kids" | null;
    category:
      | "cosmetic"
      | "endodontics"
      | "gum-care"
      | "orthodontics"
      | "preventive"
      | "prosthetics"
      | "restorative"
      | "surgery"
      | null;
    summary: string | null;
    image: ImageWithAlt | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: treatmentSlugsQuery
// Query: *[_type == "treatment" && defined(slug.current)]{ "slug": slug.current }
export type TreatmentSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: doctorsQuery
// Query: *[_type == "doctor" && defined(slug.current)] | order(order asc, name asc){  _id, name, "slug": slug.current, qualifications, specialisation, registrationNumber, bio,  "photo": photo{    alt,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  }}
export type DoctorsQueryResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  qualifications: string | null;
  specialisation: string | null;
  registrationNumber: string | null;
  bio: BlockContent | null;
  photo: {
    alt: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: faqsQuery
// Query: *[_type == "faq"] | order(order asc){ _id, question, answer, group }
export type FaqsQueryResult = Array<{
  _id: string;
  question: string | null;
  answer: string | null;
  group: "adults" | "general" | "kids" | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: testimonialsQuery
// Query: *[_type == "testimonial" && consent == true]  | order(_createdAt desc){ _id, patientName, quote, rating, source, "treatment": treatment->title }
export type TestimonialsQueryResult = Array<{
  _id: string;
  patientName: string | null;
  quote: string | null;
  rating: 1 | 2 | 3 | 4 | 5 | null;
  source: "direct" | "google" | null;
  treatment: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: galleryQuery
// Query: *[_type == "galleryItem" && (kind != "beforeAfter" || consent == true)]  | order(_createdAt desc){    _id, title, kind, image, beforeImage, afterImage, caption, "treatment": treatment->title  }
export type GalleryQueryResult = Array<{
  _id: string;
  title: string | null;
  kind: "beforeAfter" | "clinic" | null;
  image: ImageWithAlt | null;
  beforeImage: ImageWithAlt | null;
  afterImage: ImageWithAlt | null;
  caption: string | null;
  treatment: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc){  _id, title, "slug": slug.current, excerpt, coverImage, publishedAt, "author": author->name}
export type PostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: ImageWithAlt | null;
  publishedAt: string | null;
  author: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postBySlugQuery
// Query: *[_type == "post" && slug.current == $slug][0]{  _id, title, "slug": slug.current, excerpt, coverImage, body, publishedAt, seo,  "author": author->{ name, qualifications, photo }}
export type PostBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  coverImage: ImageWithAlt | null;
  body: BlockContent | null;
  publishedAt: string | null;
  seo: Seo | null;
  author: {
    name: string | null;
    qualifications: string | null;
    photo: ImageWithAlt | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: postSlugsQuery
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type PostSlugsQueryResult = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: pageBySlugQuery
// Query: *[_type == "page" && slug.current == $slug][0]{  _id, title, "slug": slug.current, body, seo}
export type PageBySlugQueryResult = {
  _id: string;
  title: string | null;
  slug: string | null;
  body: BlockContent | null;
  seo: Seo | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: recommendationsPageQuery
// Query: *[_type == "recommendationsPage"][0]{ title, intro }
export type RecommendationsPageQueryResult = {
  title: string | null;
  intro: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: recommendedProductsQuery
// Query: *[_type == "recommendedProduct"] | order(order asc, name asc){  _id, name, brand, description, link,  "image": image{    alt,    "url": asset->url,    "width": asset->metadata.dimensions.width,    "height": asset->metadata.dimensions.height  }}
export type RecommendedProductsQueryResult = Array<{
  _id: string;
  name: string | null;
  brand: string | null;
  description: string | null;
  link: string | null;
  image: {
    alt: string | null;
    url: string | null;
    width: number | null;
    height: number | null;
  } | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  name, tagline, phone, whatsapp, email,\n  "logo": logo{\n    alt,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  },\n  addressLine1, city, region, postalCode, mapsUrl, googleReviewUrl,\n  hours, socialLinks\n}': SiteSettingsQueryResult;
    '*[_type == "homePage"][0]{\n  heroHeadline, heroSubheadline, heroImage, trustStats,\n  featuredTreatments[]->{\n  _id, title, "slug": slug.current, audience, category, summary, image\n},\n  featuredDoctors[]->{ _id, name, "slug": slug.current, qualifications, specialisation, photo },\n  featuredTestimonials[]->{ _id, patientName, quote, rating, source }\n}': HomePageQueryResult;
    '*[_type == "treatment" && defined(slug.current)]\n  | order(order asc, title asc) {\n  _id, title, "slug": slug.current, audience, category, summary, image\n}': TreatmentsQueryResult;
    '*[_type == "treatment" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, audience, category, summary, image, body, faqs, seo,\n  related[]->{\n  _id, title, "slug": slug.current, audience, category, summary, image\n}\n}': TreatmentBySlugQueryResult;
    '*[_type == "treatment" && defined(slug.current)]{ "slug": slug.current }': TreatmentSlugsQueryResult;
    '*[_type == "doctor" && defined(slug.current)] | order(order asc, name asc){\n  _id, name, "slug": slug.current, qualifications, specialisation, registrationNumber, bio,\n  "photo": photo{\n    alt,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  }\n}': DoctorsQueryResult;
    '*[_type == "faq"] | order(order asc){ _id, question, answer, group }': FaqsQueryResult;
    '*[_type == "testimonial" && consent == true]\n  | order(_createdAt desc){ _id, patientName, quote, rating, source, "treatment": treatment->title }': TestimonialsQueryResult;
    '*[_type == "galleryItem" && (kind != "beforeAfter" || consent == true)]\n  | order(_createdAt desc){\n    _id, title, kind, image, beforeImage, afterImage, caption, "treatment": treatment->title\n  }': GalleryQueryResult;
    '*[_type == "post" && defined(slug.current)] | order(publishedAt desc){\n  _id, title, "slug": slug.current, excerpt, coverImage, publishedAt, "author": author->name\n}': PostsQueryResult;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, excerpt, coverImage, body, publishedAt, seo,\n  "author": author->{ name, qualifications, photo }\n}': PostBySlugQueryResult;
    '*[_type == "post" && defined(slug.current)]{ "slug": slug.current }': PostSlugsQueryResult;
    '*[_type == "page" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, body, seo\n}': PageBySlugQueryResult;
    '*[_type == "recommendationsPage"][0]{ title, intro }': RecommendationsPageQueryResult;
    '*[_type == "recommendedProduct"] | order(order asc, name asc){\n  _id, name, brand, description, link,\n  "image": image{\n    alt,\n    "url": asset->url,\n    "width": asset->metadata.dimensions.width,\n    "height": asset->metadata.dimensions.height\n  }\n}': RecommendedProductsQueryResult;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
